name: Build wheels and create release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_universal:
    name: Build Universal Wheel
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build universal wheel
      run: python -m build --wheel --outdir wheel_prebuild

    - name: Upload universal wheels
      uses: actions/upload-artifact@v4
      with:
        name: universal-wheels
        path: wheel_prebuild/*py3-none-any.whl

  create_release:
    name: Create Release with wheels
    runs-on: ubuntu-latest
    needs: build_universal
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: release_wheels

    - name: List all wheels
      run: find release_wheels -name "*.whl" | sort

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release_wheels/**/*.whl
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
